version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
        
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_ilumeo
    ports:
      - "5432:5432"
